version: '3.8'

services:
  loggingexample.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_HTTP_PORTS=${ASPNETCORE_HTTP_PORTS}
      - ASPNETCORE_HTTPS_PORTS=${ASPNETCORE_HTTPS_PORTS}
      - ASPNETCORE_URLS=http://+:${ASPNETCORE_HTTP_PORTS}
      - Redis__AbsoluteExpirationMinutes=60
      - Redis__SlidingExpirationMinutes=20
      - Redis__ConnectionString=redis:6379,password=${REDIS_PASSWORD}
      - Redis__InstanceName=LoggingExample:- 
    ports:
      - "${ASPNETCORE_HTTP_PORTS}:${ASPNETCORE_HTTP_PORTS}"
      - "${ASPNETCORE_HTTPS_PORTS}:${ASPNETCORE_HTTPS_PORTS}"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  redis:
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD} --loglevel verbose

  elasticsearch:
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"

  kibana:
    environment:
      - SERVER_NAME=kibana.local
      - SERVER_HOST=0.0.0.0

  jaeger:
    environment:
      - QUERY_BASE_PATH=/jaeger
      - LOG_LEVEL=debug
    
  kafka:
    environment:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_LOG_RETENTION_HOURS=24